### ISSUE TITLE
Where is video?

### ISSUE THREAD

**Issue by kosir** [GuerrillaCoder/Upfront-Template-Builder#5]
Wanted to test your plugin with my custom post types, but got Warning: Invalid argument supplied for foreach() ... no matter what I do. I looked for video instructions, but there is nothing on that page. Would you mind to re-upload video to youtube or somewhere? Thanks.

**Comment by GuerrillaCoder** [comment]
I restored the video.

This plugin was just a quick hack because it was impossible to make a custom template at the time.  It's not a well polished user friendly plugin.

Incsub promised that this would be core functionality before the end of 2015 so it might be worth checking with them to see where the status of this is.

**Comment by kosir** [comment]
Thanks & thanks. I'll try their plugin.
